(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var D0=function(a){a.V("cardstatechange",a.Lg()&&a.Ti()?1:0)},E0=function(a,b){var c=g.Ma(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},kDa=function(a){var b=g.Ig(a);
a=g.Og(a);return new g.hg(b.x,b.y,a.width,a.height)},lDa=function(a){return Math.pow(a,3)},mDa=function(a){return 3*a*a-2*a*a*a},H0=function(a){a=g.Qa(a);
delete F0[a];g.Qb(F0)&&G0&&G0.stop()},oDa=function(){G0||(G0=new g.E(function(){nDa()},20));
var a=G0;a.isActive()||a.start()},nDa=function(){var a=g.A();
g.Db(F0,function(b){pDa(b,a)});
g.Qb(F0)||oDa()},I0=function(a,b,c,d){g.Dn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.K=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.I=0;this.D=null},pDa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.I=1E3/(b-a.D);a.D=b;qDa(a,a.progress);1==a.progress?(a.La=0,H0(a),a.onFinish(),a.Zr()):a.Gb()&&a.ny()},qDa=function(a,b){"function"===typeof a.F&&(b=a.F(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.K[c]-a.u[c])*b+a.u[c]},rDa=function(a,b){g.Ll.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.I;this.state=b.La},J0=function(a,b,c,d,e){I0.call(this,b,c,d,e);
this.element=a},K0=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
J0.call(this,a,b,c,d,e)},L0=function(a){g.B.call(this);
this.B=a||window;this.u=[]},M0=function(a){return a.baseUrl||null},N0=function(a,b){return g.Ne(g.Mc(a,b,void 0),function(c){return!!c})},sDa=function(a,b,c){function d(Pa){var eb,uc,wb,Hb=Pa.hovercardButton;
if(!Hb)return null;Hb=Hb.subscribeButtonRenderer;if(!Hb)return null;var xd=f(Hb.unsubscribedButtonText),yd=f(Hb.subscribedButtonText);if(Hb.subscribed){var Of=f(Hb.subscriberCountWithUnsubscribeText);var Ke=f(Hb.subscriberCountText)}else Of=f(Hb.subscriberCountText),Ke=f(Hb.subscriberCountWithSubscribeText);var Ld=null;return Pa.signinEndpoint&&(Ld=E0(Pa,"signinEndpoint","webNavigationEndpointData","url"),Ld||(Ld=null===(wb=null===(uc=null===(eb=Hb.signInEndpoint)||void 0===eb?void 0:eb.commandMetadata)||
void 0===uc?void 0:uc.webCommandMetadata)||void 0===wb?void 0:wb.url),!Ld)?null:xd&&(yd||Ld)?{subscribed:Hb.subscribed,subscribeText:xd,subscribeCount:Of,unsubscribeText:yd,unsubscribeCount:Ke,enabled:Hb.enabled,signinUrl:Ld,classic:Pa.useClassicSubscribeButton}:null}
function e(Pa){if(Pa){var eb=[],uc=Pa.videoId;uc&&eb.push("v="+uc);(uc=Pa.playlistId)&&eb.push("list="+uc);(Pa=Pa.startTimeSeconds)&&eb.push("t="+Pa);return"/watch?"+eb.join("&")}}
function f(Pa){if(!Pa)return null;var eb=Pa.simpleText;return eb?eb:Pa.runs?g.Mc(Pa.runs,function(uc){return uc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,w=null,x=!1,y=null,F=null,D=null,G=null,H=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=E0(l,"browseEndpoint","browseId"))w=x,m="/channel/"+w;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):F=f(b.subscribersText)}else"WEBSITE"===
h?((D=E0(l,"urlEndpoint","url"))&&(m=D),n=!0,p="new",D=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(H=f(b.additionalFeesText)),(n=E0(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=E0(b,"title","accessibility","accessibilityData","label");var I=b.endpoint?b.endpoint.clickTrackingParams:null,za="";if(b.metadata){var ha=f(b.metadata);ha&&(za=ha)}return{id:"element-"+c,type:h,title:f(b.title),metadata:za,callToAction:f(b.callToAction),
CC:b.image,iconUrl:D,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:w,subscribeButton:y,subscribersText:F,isSubscribe:x,targetUrl:m||null,HK:n,Bd:I?{itct:I}:null,rR:p,mq:a?a:null,KK:b.isPlaceholder,impressionUrls:N0(b.impressionUrls||[],M0),zK:N0(b.hovercardShowUrls||[],M0),clickUrls:N0(l.loggingUrls||[],M0),visualElement:g.du(b.trackingParams),
productPrice:G,additionalFeesText:H}},O0=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:N0(a.impressionUrls||[],M0),elements:N0(a.elements||[],function(d,e){return sDa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.du(a.trackingParams));return c},P0=function(a){g.hO.call(this,a);
this.C=this.endscreen=null;this.u={};this.F={};this.D=this.B=null;this.K=[];this.U=!0;this.I=0;a=a.S();this.N=g.xD(a)||g.zD(a);this.events=new g.YN(this);g.C(this,this.events);this.events.P(this.player,g.xG("creatorendscreen"),this.yd);this.events.P(this.player,g.yG("creatorendscreen"),this.qf);this.events.P(this.player,"resize",this.Ra);this.events.P(window,"focus",this.pQ);this.load();var b=g.Ge("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.dg(this,function(){g.Me(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},tDa=function(a){return a.player.getVideoData().F?"current":a.N?"new":"current"},Q0=function(a){return"creator-endscreen-editor"===a.player.S().playerStyle},uDa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=O0(f,tDa(a))));R0(a,f)},
urlParams:{v:c},withCredentials:!0};a.N&&(c.urlParams.ptype="embedded");var d=b.tm;d&&(c.postParams={ad_tracking:d});if(b=g.rja(b))if(b=g.Hc(b),b=g.Dc(b))a.C=g.yq(b,c)},R0=function(a,b,c){c=void 0===c?!0:c;
a.player.Re("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.q(Object.values(a.u)),e=d.next();!e.done;e=d.next())e.value.dispose();a.u={};a.F={};0<a.K.length&&(a.K.forEach(function(l){l.dispose()}),a.K.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&vDa(a);c=[];d=new g.uG(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.S().u||(a.B=new g.U({G:"div",L:"ytp-ce-shadow"}),g.WN(a.player,a.B.element,4),a.D=new g.EM(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=wDa(a,e);if(f){a.u[e.id]=f;a.F[e.id]=e;g.WN(a.player,f.element,4);var h=new g.uG(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);xDa(a,f,e)}else g.Pr(new g.Vr("buildEndscreenElement null",
e))}a.player.Jd(c);a.Ra()}},vDa=function(a){var b=g.hu(),c=g.ju();
c&&b&&a.endscreen.visualElement&&g.xu(c,b,a.endscreen.visualElement)},wDa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Y("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={G:"div",ia:["ytp-ce-element","ytp-ce-video"],T:{tabindex:"0","aria-label":b.mq||"","aria-hidden":"true"},R:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",T:S0(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",T:{href:T0(a,b.targetUrl),tabindex:"-1"},R:[{G:"div",ia:["ytp-ce-video-title"].concat(g.ma(c)),T:{dir:g.Jn(b.title||
"")},ba:b.title},{G:"div",L:"ytp-ce-video-duration",ba:b.videoDuration||void 0}]}]};c=new g.U(c);break;case "PLAYLIST":c=a.player.Y("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];c={G:"div",ia:["ytp-ce-element","ytp-ce-playlist"],T:{tabindex:"0","aria-label":b.mq||"","aria-hidden":"true"},R:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-covering-image",T:S0(b)},{G:"div",L:"ytp-ce-covering-shadow-top"},{G:"a",L:"ytp-ce-covering-overlay",T:{href:T0(a,
b.targetUrl),tabindex:"-1"},R:[{G:"div",ia:["ytp-ce-playlist-title"].concat(g.ma(c)),T:{dir:g.Jn(b.title||"")},ba:b.title},{G:"div",L:"ytp-ce-playlist-count",R:[{G:"div",L:"ytp-ce-playlist-icon"},{G:"div",L:"ytp-ce-playlist-count-text",ba:b.playlistLength||void 0}]}]}]};c=new g.U(c);break;case "CHANNEL":c={G:"div",ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],T:{tabindex:"0","aria-label":b.mq||"","aria-hidden":"true"},R:[{G:"div",L:"ytp-ce-element-shadow"},
{G:"div",L:"ytp-ce-expanding-overlay",R:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",R:[{G:"div",L:"ytp-ce-expanding-overlay-body",R:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{G:"a",ia:["ytp-ce-channel-title","ytp-ce-link"],T:{href:T0(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Jn(b.title||"")},ba:b.title},b.subscribeButton?{G:"div",L:"ytp-ce-subscribe-container",R:[{G:"div",L:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{G:"div",L:"ytp-ce-channel-subscribers-text",ba:b.subscribersText}:"",b.metadata?{G:"div",ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],ba:b.metadata}:""]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",T:S0(b)}]};c=new g.U(c);var d=g.se(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.J(d,"ytp-ce-subscribe-button");if(a.player.S().u){var e=null;var f=b.Bd.itct}else e="endscreen",f=null;e=new g.iP(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.K.push(e)}break;case "WEBSITE":c={G:"div",ia:["ytp-ce-element","ytp-ce-website"],T:{tabindex:"0","aria-label":b.mq||"","aria-hidden":"true"},R:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",R:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},
{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",R:[{G:"div",L:"ytp-ce-expanding-overlay-body",R:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{G:"div",L:"ytp-ce-website-title",T:{dir:g.Jn(b.title||"")},ba:b.title},{G:"div",L:"ytp-ce-website-metadata",ba:b.metadata},{G:"a",ia:["ytp-ce-website-goto","ytp-ce-link"],T:{href:T0(a,b.targetUrl),target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},{G:"div",L:"ytp-ce-expanding-image",T:S0(b)},{G:"div",
L:"ytp-ce-expanding-icon",T:yDa(b.iconUrl)}]};c=new g.U(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",L:"ytp-ce-merchandise-price-container",R:[{G:"div",L:"ytp-ce-merchandise-price",ba:b.productPrice}]},b.additionalFeesText&&c.R.push({G:"div",L:"ytp-ce-merchandise-additional-fees",ba:b.additionalFeesText})),c={G:"div",ia:["ytp-ce-element","ytp-ce-merchandise"],T:{tabindex:"0","aria-label":b.mq||"","aria-hidden":"true"},R:[{G:"div",L:"ytp-ce-element-shadow"},{G:"div",L:"ytp-ce-expanding-overlay",
R:[{G:"div",L:"ytp-ce-expanding-overlay-hider"},{G:"div",L:"ytp-ce-expanding-overlay-background"},{G:"div",L:"ytp-ce-expanding-overlay-content",R:[{G:"div",L:"ytp-ce-expanding-overlay-body",R:[{G:"div",L:"ytp-ce-expanding-overlay-body-padding",R:[{G:"div",L:"ytp-ce-merchandise-title",T:{dir:g.Jn(b.title||"")},ba:b.title},c,{G:"div",L:"ytp-ce-merchandise-metadata",ba:b.metadata},{G:"a",ia:["ytp-ce-merchandise-goto","ytp-ce-link"],T:{href:T0(a,b.targetUrl),target:"_blank",tabindex:"-1"},ba:b.callToAction}]}]}]}]},
{G:"div",L:"ytp-ce-expanding-image",T:S0(b)},{G:"div",L:"ytp-ce-merchandise-invideo-cta-container",R:[{G:"div",L:"ytp-ce-merchandise-invideo-cta",ba:b.callToAction||void 0}]}]},c=new g.U(c)}b.KK&&g.J(c.element,"ytp-ce-placeholder");return c},S0=function(a){if(a.CC)var b=a.CC.thumbnails;
return yDa(b?b[b.length-1].url:null)},yDa=function(a){return a?{style:"background-image: url("+a+")"}:{}},xDa=function(a,b,c){function d(m){m&&(b.ya("blur",function(){"none"!=m.style.display&&a.U&&m.focus()}),b.P(m,"focus",f),b.P(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.J(b.element,"ytp-ce-force-expand"),U0(a,c.id,!0)):(g.An(b.element,"ytp-ce-force-expand"),g.An(b.element,"ytp-ce-element-hover"),U0(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.ya("mouseenter",function(){V0(a,b,c)});
b.ya("mouseleave",function(){W0(a,b,c)});
a.player.S().u||b.ya("click",function(){g.J(b.element,"ytp-ce-element-hover")});
b.ya("click",function(m){zDa(a,c,m)});
b.ya("keypress",function(m){zDa(a,c,m)});
b.ya("focus",function(){V0(a,b,c)});
b.ya("blur",function(){W0(a,b,c)});
b.ya("touchstart",function(){V0(a,b,c)});
var l=g.ue("ytp-ce-expanding-overlay-hider",b.element);l&&b.P(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.An(b.element,"ytp-ce-element-hover");g.An(b.element,"ytp-ce-force-expand")});
b.ya("keydown",function(m){a.U=9===m.keyCode&&!m.shiftKey});
d(g.ue("ytp-sb-subscribe",b.element));d(g.ue("ytp-sb-unsubscribe",b.element));b.ya("focus",f);b.ya("blur",h)},zDa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.yn(d,"ytp-ce-element");){g.yn(d,"subscribe-label")&&X0(a,b);
if(g.yn(d,"ytp-ce-channel-subscribe"))return;d=g.Oe(d)}if(!d||g.yn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.u[b.id])W0(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.rR)X0(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Hc(T0(a,b.targetUrl)),c=g.Dc(c),g.EK(c,void 0,b.Bd);else{var e=a.player.getVideoData().F,f=function(){var h=T0(a,b.targetUrl),l=b.Bd,m=g.gq(h);e&&m&&(m.v||m.list)?a.player.Ki(m.v,l,m.list,!1):g.DK(h,l)};
X0(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},T0=function(a,b){var c=a.player.S();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.eE(c)+b}else return"";return b},V0=function(a,b,c){g.yn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.J(b.element,"ytp-ce-element-hover"):a.player.S().u?(new g.E(function(){g.J(b.element,"ytp-ce-element-hover")},200)).start():g.J(b.element,"ytp-ce-element-hover"),Y0(a,c.zK),U0(a,c.id,!0))},W0=function(a,b,c){g.An(b.element,"ytp-ce-element-hover");
g.An(b.element,"ytp-ce-force-expand");U0(a,c.id,!1)},U0=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.q(Object.keys(a.u)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.K(a.u[e].element,"ytp-ce-element-shadow-show",c)},Y0=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||Q0(a))c&&c();else{b=ADa(a,b);var e=0,f=!1,h=new g.E(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Ju(b[a],d)}},X0=function(a,b,c){Y0(a,b.clickUrls,c);
(a=g.ju())&&b.HK&&g.Au(a,b.visualElement)},ADa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(a.Yz(b[e],c));return d},BDa=function(a){return Array.isArray(a)&&a.length?a[0]:a},Z0=function(a){return"string"===typeof a?a:""},$0=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},CDa=function(a){this.externalId=a},DDa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.u=d},a1=function(a){return a.value?a.value:null},b1=function(a){if(!a)return null;
var b=g.Hc(Z0(a.value));b=g.Dc(b);if(!b)return null;var c=$0(a.target,EDa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new DDa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},FDa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},IDa=function(a){if(!a)return null;
var b=$0(a.type,GDa),c=$0(a.trigger,HDa),d=BDa(a.url);d=b1(d?d:null);a=BDa(a.subscribeData);var e=a?a:null;e?(a=Z0(e.external_user_id),e=Z0(e.subscription_token),a=a&&e?new CDa(a):null):a=null;return b?new FDa(b,c,d,a):null},JDa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},LDa=function(a){return(a=KDa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},KDa=function(a,b){return g.cb(a.action,b,void 0)},MDa=function(a,b){this.context=a;
this.u=b},d1=function(a){return a.customMessage?c1("div","iv-card-message",a.customMessage):""},e1=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{G:"div",L:"iv-card-image",T:{style:c},R:d}},f1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(c1("li","",c.value));return{G:"ul",L:"iv-card-meta-info",R:b}},c1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Jn(c);return{G:a,T:b,ba:c}},NDa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.jt&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.jt+");");c.dir=g.Jn(a.customMessage);var d=[{G:"span",ba:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",L:"iv-card-link-icon"}));return{G:"div",ia:b,T:c,R:d}},g1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.u(e.value,d,c.id,c.Bd,c.og.click,5)}},ODa=function(a,b){this.merchant=a;
this.price=b},PDa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},QDa=function(a,b){return b?b:PDa(a)?"current":"new"},h1=function(a,b){g.B.call(this);
var c=this;this.element=a;this.context=b;this.Ia=!1;this.wa=new Map;this.Aa=new Map;this.context.J.addEventListener(g.xG("annotations_module"),function(d){(d=c.wa.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.yG("annotations_module"),function(d){(d=c.Aa.get(d))&&d.apply(c)})},i1=function(a,b,c,d,e,f,h){a.context.u.ya(b,"click",function(l){a.kz(c,d,e,f||[],h||0,l)});
a.context.u.ya(b,"touchstart",function(){a.Ia=!1});
a.context.u.ya(b,"touchmove",function(){a.Ia=!0})},RDa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},j1=function(a,b,c){return{GD:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
wH:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Rv:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},m1=function(a,b,c){h1.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.ea=this.Xa=this.C=this.de=!1;this.ka=null;this.cards=[];this.Oa=this.N=this.ga=this.F=this.la=this.u=null;this.W=[];this.K=this.Td=this.da=null;this.I=0;this.Z=new g.E(g.Ja,c.D.Gd?4E3:3E3);g.C(this,this.Z);this.Ga=new g.E(g.Ja);g.C(this,this.Ga);this.X=new MDa(c,function(e,f,h,l,m,n){i1(d,e,f,h,l,m,n)});
this.U=new g.U({G:"div",L:"iv-drawer",T:{id:"iv-drawer"},R:[{G:"div",L:"iv-drawer-header",T:{"aria-role":"heading"},R:[{G:"span",L:"iv-drawer-header-text"},{G:"button",ia:["iv-drawer-close-button","ytp-button"],T:{"aria-label":"Hide cards",tabindex:"0"}}]},{G:"div",L:"iv-drawer-content"}]});g.C(this,this.U);this.D=this.U.element;this.Ha=new g.EM(this.U,330);g.C(this,this.Ha);this.Ua=g.ue("iv-drawer-header-text",this.D);this.B=g.ue("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Xa&&k1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Xa=d.C)&&l1(d)})},SDa=function(a,b){var c=b.data;
c.autoOpenMs&&a.addCueRange(c.autoOpenMs,0x8000000000000,"",function(){k1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
c.autoCloseMs&&a.addCueRange(c.autoCloseMs,0x8000000000000,"",function(){l1(a)});
var d=c.headerText;g.Qe(a.Ua,d);a.N&&a.N.setAttribute("title",d);c.eventId&&(a.eventId=c.eventId);a.da=g.du(c.trackingParams);a.K=g.du(c.closeTrackingParams);a.Td=g.du(c.iconTrackingParams)},TDa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"simple",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:n1(a,c,b,d),sponsored:!1,og:j1(d,e,d.command),ak:d.trackingParams?g.du(d.trackingParams):null,Nh:e.trackingParams?g.du(e.trackingParams):
null,Td:f&&f.trackingParams?g.du(f.trackingParams):null,imageUrl:o1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,jt:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?b1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};p1(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:n1(a,c,b,d),sponsored:!1,og:j1(d,e,d.endpoint),ak:d.trackingParams?g.du(d.trackingParams):null,Nh:e.trackingParams?g.du(e.trackingParams):null,Td:f&&f.trackingParams?g.du(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.S(d.customText):null,DG:o1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:b1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};p1(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:n1(a,c,b,d),sponsored:!1,og:j1(d,e,d.action),ak:d.trackingParams?g.du(d.trackingParams):null,Nh:e.trackingParams?g.du(e.trackingParams):null,Td:f&&f.trackingParams?g.du(f.trackingParams):
null,Ps:o1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:b1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:RDa(d.action)})};p1(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.I,type:"video",teaserText:g.S(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Bd:n1(a,c,b,d),sponsored:!1,og:j1(d,e,d.action),ak:d.trackingParams?g.du(d.trackingParams):null,Nh:e.trackingParams?g.du(e.trackingParams):null,Td:f&&f.trackingParams?g.du(f.trackingParams):null,Ps:o1(d.videoThumbnail.thumbnails,258).url,
videoDuration:d.lengthString?g.S(d.lengthString):null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:b1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:RDa(d.action)})};p1(a,c)}a.I++},o1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},n1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},VDa=function(a,b){var c=UDa(a,b);
c&&(c===a.u&&(a.u=null),a.J.removeCueRange(c.card.id),g.Me(c.ix),g.lb(a.cards,c),a.lt(),q1(a))},k1=function(a,b,c){if(!a.C){a.Ha.show();
a.la=new g.E(function(){g.J(a.context.J.getRootNode(),g.nT.IV_DRAWER_OPEN)},0);
a.la.start();a.ka=g.kp(a.B,"mousewheel",function(h){a.Z.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.ju();d&&a.da&&a.K&&g.yu(d,[a.da,a.K]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.lE||(f.lE=!0,WDa(a.context.logger,f.card.og.GD,b)),d&&g.yu(d,[f.card.ak]);D0(a.J);c&&(a.F=new g.E(function(){a.ga=a.N;a.Oa.focus()},330),a.F.start())}},l1=function(a){a.C&&(a.Ha.hide(),g.lp(a.ka),a.ka=null,g.An(a.context.J.getRootNode(),g.nT.IV_DRAWER_OPEN),a.C=!1,D0(a.J),a.F&&a.F.stop(),a.F=new g.E(function(){a.ga&&(a.ga.focus(),a.ga=null)},330),a.F.start())},YDa=
function(a){g.zn(a.element,[g.nT.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.WN(a.J,a.D,5);XDa(a);a.N=g.ue("ytp-cards-button",a.J.getRootNode());a.Oa=g.ue("iv-drawer-close-button",a.D);a.de=!0},XDa=function(a){var b=g.ue("iv-drawer-close-button",a.D);
a.context.u.ya(b,"click",a.gJ,a);a.context.u.ya(a.B,"touchend",function(){a.Z.start()});
a.context.u.ya(a.B,"scroll",a.rJ,a);a.context.B.subscribe("onHideControls",function(){a.ea=!0});
a.context.B.subscribe("onShowControls",function(){a.ea=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.ea=g.yn(a.J.getRootNode(),"ytp-autohide")});
a.W.push(g.Qo("iv-button-shown",a.QK,a));a.W.push(g.Qo("iv-button-hidden",a.PK,a));a.W.push(g.Qo("iv-teaser-shown",a.NL,a));a.W.push(g.Qo("iv-teaser-hidden",a.SK,a));a.W.push(g.Qo("iv-teaser-clicked",a.ML,a))},p1=function(a,b){a.de||YDa(a);
VDa(a,b.id);var c=ZDa(a,b);if(c){var d={card:b,ix:c.element,lE:!1},e=$Da(a,d);g.sb(a.cards,e,0,d);c.fa(a.B,e);a.lt();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.u=d,q1(a),aEa(a,d),k1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&bEa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){bEa(a,d)}),q1(a))}},ZDa=function(a,b){switch(b.type){case "simple":var c=a.X;
var d=b.displayDomain?{G:"div",L:"iv-card-image-text",ba:b.displayDomain}:void 0;var e=NDa(b);d={G:"div",ia:["iv-card"],R:[{G:"a",L:"iv-click-target",T:{href:b.url?a1(b.url)||"":""},R:[e1(b.imageUrl,d),{G:"div",L:"iv-card-content",R:[c1("h2",void 0,b.title),e]}]}]};d=new g.U(d);g1(c,g.te("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.X,d={G:"div",ia:["iv-card","iv-card-channel"],R:[{G:"a",ia:["iv-click-target"],T:{href:a1(b.url)||"","data-ytid":b.channelId},R:[e1(b.DG),
{G:"div",L:"iv-card-content",R:[d1(b),{G:"h2",L:"iv-card-primary-link",ba:b.title},f1(b)]}]}]},d=new g.U(d),g1(c,g.te("iv-click-target",d.element),b,b.url),d;case "playlist":return c=a.X,d={G:"div",ia:["iv-card","iv-card-playlist"],R:[{G:"a",L:"iv-click-target",T:{href:a1(b.url)||""},R:[e1(b.Ps,{G:"div",L:"iv-card-image-overlay",R:[{G:"span",L:"iv-card-playlist-video-count",ba:b.playlistVideoCount}]}),{G:"div",L:"iv-card-content",R:[d1(b),c1("h2","iv-card-primary-link",b.title),f1(b)]}]}]},d=new g.U(d),
g1(c,g.te("iv-click-target",d.element),b,b.url),d;case "productListing":c=a.X;var f=!g.ib(b.offers);d=["iv-card"];e="";var h=NDa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({G:"div",L:"iv-card-offer-price",ba:h.price}),h.merchant&&f.push({G:"div",L:"iv-card-offer-merchant",ba:h.merchant}),h={G:"div",R:f});f=b.url?a1(b.url)||"":"";d={G:"div",ia:d,T:{tabindex:"0"},R:[{G:"a",ia:["iv-card-image","iv-click-target"],T:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{G:"div",L:"iv-card-content",R:[b.sponsored?{G:"div",L:"iv-card-sponsored",R:["Sponsored",{G:"div",L:"iv-ad-info-container",R:[{G:"div",L:"iv-ad-info",ba:"{{adInfo}}"},{G:"div",L:"iv-ad-info-icon-container",R:[{G:"div",L:"iv-ad-info-icon"},{G:"div",L:"iv-ad-info-callout"}]}]}]}:"",{G:"a",L:"iv-click-target",T:{href:f},R:[c1("h2",e,b.title),h]}]}]};d=new g.U(d);e=g.Ge("span");g.Qe(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
d.Fc(e,"adInfo");g1(c,g.te("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.X,e=b.videoDuration?{G:"span",L:"iv-card-video-duration",ba:b.videoDuration}:void 0,h=b.isLiveNow?{G:"span",ia:["yt-badge","yt-badge-live"],ba:"LIVE NOW"}:null,e={G:"div",ia:["iv-card","iv-card-video"],R:[{G:"a",L:"iv-click-target",T:{href:(null===(d=b.url)||void 0===d?void 0:a1(d))||""},R:[e1(b.Ps,e),{G:"div",L:"iv-card-content",R:[d1(b),c1("h2","iv-card-primary-link",b.title),f1(b),h]}]}]},d=new g.U(e),
g1(c,g.te("iv-click-target",d.element),b,b.url),d;default:return null}},$Da=function(a,b){if(0===a.cards.length)return 0;
var c=g.db(a.cards,function(d){return b.card.startMs>d.card.startMs||b.card.startMs===d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1===c?0:c+1},cEa=function(a){return a.u?"productListing"===a.u.card.type:g.xh(a.cards,function(b){return"productListing"===b.card.type})},q1=function(a){g.K(a.J.getRootNode(),"ytp-cards-shopping-active",cEa(a))},bEa=function(a,b){if(!g.yn(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.u!==b){var c=g.ju(),d=a.u?a.u.card.Td:a.Td;
c&&d&&g.zu(c,[d]);a.u=b;q1(a)}if(c="none"!=a.element.style.display)2===a.context.J.getPresentingPlayerType()?c=1===a.context.J.getAdState():(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=1===c||3===c||d);c&&b.card.teaserDurationMs&&a.J.Tp(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ga.isActive()||((!a.C||!a.Z.isActive()&&a.ea)&&aEa(a,b),a.Ga.start(910+b.card.teaserDurationMs))}},aEa=function(a,b){if(a.U.bb){var c=new I0([0,
a.B.scrollTop],[0,b.ix.offsetTop],600,mDa);a.context.C.ya(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.C.ya(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.SL(a.U,!0),a.B.scrollTop=b.ix.offsetTop,g.SL(a.U,!1)},r1=function(a){return a.u&&a.u.card?a.u.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},UDa=function(a,b){return g.cb(a.cards,function(c){return c.card.id===b})},s1=function(a,b,c){h1.call(this,a,b);
this.annotation=c;this.isActive=!1},dEa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},t1=function(a,b,c){s1.call(this,a,b,c);
this.B=null;this.K=!1;this.C=null;this.D=!1;this.u=this.I=this.F=null},eEa=function(a,b){var c=void 0===c?0:c;
var d=kDa(b).width;g.Gg(b,d);c=new K0(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,lDa);g.C(a,c);a.context.C.ya(c,"begin",function(){g.Pg(b,!0)});
c.play()},hEa=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
ia:["iv-branding-context-name"],ba:b.channel_name}),d=a.createElement({G:"div",ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.u=new g.iP(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.J),a.u.fa(d));var f=a.createElement({G:"div",ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",ia:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Pg(h,!1);var l=a.createElement({G:"div",ia:["branding-context-container-outer"]});l.appendChild(h);g.xg(l,"right",b.image_width+"px");a.element.appendChild(l);a.C=new g.E(function(){fEa(a,h,l)},500);
g.C(a,a.C);a.context.u.ya(a.element,"mouseover",function(){gEa(a,h,l,f,b.image_height)});
a.context.u.ya(a.element,"mouseout",function(){a.C.start()})}},gEa=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Og(b);a.u||(b.style.width=g.Fg(f.width,!0),c.style.width=g.Fg(f.width,!0));g.xg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.xg(d,"right","1px");a.D=!0;g.Pg(b,!0);a.F=new g.E(function(){g.J(this.element,"iv-branding-active")},0,a);
a.F.start()}},fEa=function(a,b,c){g.An(a.element,"iv-branding-active");
a.I=new g.E(function(){g.Pg(b,!1);a.u||(c.style.width=g.Fg(0,!0))},250);
a.I.start();a.D=!1},iEa=function(a,b,c,d,e,f,h){this.u=a;
this.C=b;this.D=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},u1=function(a,b,c){s1.call(this,a,b,c);
var d=this;this.N=this.isCollapsed=this.U=!1;this.I=5E3;this.B=this.C=this.u=this.D=null;this.K=this.createElement({G:"div",ia:["iv-promo-contents"]});this.F=new g.E(function(){d.u.setAttribute("aria-hidden","true");g.Pg(d.C,!1);g.Pg(d.B,!0)},700,this);
g.C(this,this.F)},jEa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=LDa(a.annotation),f=b.image_url;if(f){var h=a.createElement({G:"div",ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",T:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({G:"span",L:"iv-promo-video-duration",ba:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",L:"iv-promo-playlist-length",ba:b.playlist_length.toString()}),h.appendChild(f));e&&i1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",L:"iv-promo-txt"}),g.gd(f,a1(e)),a.u=f):a.u=a.createElement({G:"div",L:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",R:[{G:"strong",
ba:b.text_line_1}]});var m=a.createElement({G:"p",R:[{G:"span",L:"iv-promo-link",ba:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",ia:["iv-button","iv-promo-button"],R:[{G:"span",L:"iv-button-content",ba:f}]});var p=a.createElement({G:"div",L:"iv-promo-button-container"});p.appendChild(f);e&&i1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.J(a.u,
"iv-click-target");e&&i1(a,a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",R:[{G:"span",ba:b.text_line_1}]}),m=a.createElement({G:"p",R:[{G:"strong",ba:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",ia:["yt-badge","iv-promo-badge-live"],ba:"LIVE NOW"})),g.J(a.u,"iv-click-target"),e&&i1(a,a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.K.appendChild(a.u);p&&
a.K.appendChild(p);c=a.createElement({G:"div",L:"iv-promo-actions"});a.B=a.createElement({G:"button",ia:["iv-promo-expand","ytp-button"]});a.B.title="Expand";a.context.u.ya(a.B,"click",function(r){v1(a,5E3,r)});
c.appendChild(a.B);g.Pg(a.B,!1);a.context.u.ya(a.element,"mouseover",a.hK,a);a.context.u.ya(a.element,"mouseout",a.gK,a);a.context.u.ya(a.element,"touchend",function(r){v1(a,5E3,r)});
a.C=a.createElement({G:"button",ia:["iv-promo-close","ytp-button"]});a.C.title="Close";a.context.u.ya(a.C,"click","cta"===a.annotation.style&&b.text_line_3?a.bK:a.aK,a);c.appendChild(a.C);g.zn(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.K);a.element.appendChild(c)},v1=function(a,b,c){c.stopPropagation();
kEa(a);lEa(a,b);a.u.focus()},mEa=function(a){a.isCollapsed||a.N||a.D||(g.J(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.F.start())},kEa=function(a){a.F.stop();
a.isCollapsed&&(g.Bn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Pg(a.B,!1),g.Pg(a.C,!0))},lEa=function(a,b){a.D||(a.D=g.Sm(function(){w1(this);
mEa(this)},b,a))},w1=function(a){a.D&&(g.v.clearTimeout(a.D),a.D=null)},nEa=function(a){this.J=a},WDa=function(a,b,c){b&&(c?x1(a,b.map(function(d){return g.mn(d,c)})):x1(a,b))},x1=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Ju(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},y1=function(a){g.hO.call(this,a);
var b=this;this.U=!1;this.loadNumber=0;this.K={};this.logger=new nEa(this.player);this.F=new g.YN(this);this.I=this.C=null;this.events=new g.YN(this);this.N=this.u=null;this.W=[];g.C(this,this.F);this.F.P(this.player,"onVideoAreaChange",function(){b.V("onVideoAreaChange")});
this.F.P(this.player,"onHideControls",function(){b.V("onHideControls")});
this.F.P(this.player,"onShowControls",function(){b.V("onShowControls")});
this.F.P(this.player,"resize",function(d){b.V("resize",d)});
this.F.P(this.player,"presentingplayerstatechange",function(d){b.V("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.LL,this);this.subscribe("resize",this.hv,this);this.player.S().N.subscribe("vast_info_card_add",this.pG,this);g.C(this,this.events);this.X=this.createElement({G:"div",L:"video-custom-annotations"});this.B=new g.U({G:"div",ia:["ytp-player-content","ytp-iv-player-content"]});g.C(this,this.B);g.WN(this.player,this.B.element,4);this.B.hide();this.D=new g.U({G:"div",ia:["ytp-iv-video-content"]});g.C(this,this.D);a=this.createElement({G:"div",L:"video-annotations"});
a.appendChild(this.X);this.D.element.appendChild(a);this.Un()&&this.load();var c=this.createElement({G:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.dg(this,function(){g.Me(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},oEa=function(a){a=a.createElement({G:"div",
ia:["annotation","annotation-type-custom"]});g.Pg(a,!1);return a},pEa=function(a,b){var c=!b.isCued()&&!g.T(b,1024);
g.SL(a.B,c);g.SL(a.D,c)},qEa=function(a,b,c){a.U=!0;
a.I=g.yq(b,c)},rEa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(rEa(a,e))}return c},uEa=function(a){var b=a.player.getVideoData();
if(b.da){var c=a.player.S().N.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.sq(h)&&h.responseXML?h.responseXML:null)&&z1(a,h)}};
g.Bp()&&(d.onFinish=sEa(a,d.onFinish));d.postParams={ic_only:"1"};tEa(d,c);a.U=!0;g.yq(b.da,d)}}},tEa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.zq&&(a.postParams.ic_coll=b.zq);b.qt&&(a.postParams.ic_xml=b.qt);b.Ss&&(a.postParams.ic_track=b.Ss)},vEa=function(a){var b=new g.U({G:"div"});
g.Pg(b.element,!1);var c=new m1(a.player,b.element,A1(a));g.C(c,b);b.fa(a.B.element);c.Es();return c},A1=function(a){if(!a.N){var b=new L0(a);
g.C(a,b);var c=new g.p_(a);g.C(a,c);a.N=new iEa(b,c,a.player.S(),a.player.getVideoData(),a.logger,a.player,a.Gd)}return a.N},z1=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.ju();if(e){var f=g.hu();f&&g.pu(g.Zo("use_default_events_client")?void 0:g.Xs,e,f,[g.du(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var h=rEa(a,d[e]);f=null;try{if(h){var l=h.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var p=$0(h.type,wEa),r=$0(h.style,xEa),t=Z0(h.data),w=0!==t.length?JSON.parse(t):{};var x=h.action;h=IDa;if(null==x)var y=null;else if(g.Ma(x)){m=[];for(var F=g.q(x),D=F.next();!D.done;D=
F.next()){var G=h(D.value);G&&m.push(G)}y=m}else{var H=h(x);y=H?[H]:[]}f=n&&p?new JDa(n,p,r,y,w):null}else f=null}catch(uc){}if(f)if("branding"===f.type||"promotion"===f.type){h=a;m=f;var I=oEa(h),za=null;switch(m.type){case "branding":if(h.player.S().Eb)break;h.B.element.appendChild(I);za=new t1(I,A1(h),m);break;case "promotion":g.WN(h.player,I,4),za=new u1(I,A1(h),m)}za&&za.Es();if(h=za)g.C(a,h),a.K[f.id]=h}else if("card"===f.type||"drawer"===f.type){a.u||(a.u=vEa(a),g.C(a,a.u));if("card"===f.type){c=
a.u;var ha=f&&f.data&&f.data.card_type;h=f.data;if(ha)switch(m=h.tracking||{},m={GD:m.impression,click:m.click,close:m.close,wH:m.teaser_impression,Rv:m.teaser_click},I=h.tracking_params||{},za=null,ha){case "collaborator":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,og:m,ak:I.card?g.du(I.card):null,Nh:I.teaser?g.du(I.teaser):null,Td:I.icon?
g.du(I.icon):null,channelId:h.channel_id,customMessage:h.custom_message?h.custom_message:null,DG:h.image_url,title:h.title,metaInfo:h.meta_info,url:b1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};p1(c,f);break;case "playlist":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,og:m,ak:I.card?g.du(I.card):null,
Nh:I.teaser?g.du(I.teaser):null,Td:I.icon?g.du(I.icon):null,Ps:h.image_url,playlistVideoCount:h.playlist_video_count,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,url:b1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};p1(c,f);break;case "productListing":h.signin_url&&(za=b1({target:"current",value:h.signin_url}));ha=[];for(var Pa=h.offers||[],eb=0;eb<Pa.length;eb++)ha.push(new ODa(g.nd(Pa[eb].merchant),g.nd(Pa[eb].price)));
f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,og:m,ak:I.card?g.du(I.card):null,Nh:I.teaser?g.du(I.teaser):null,Td:I.icon?g.du(I.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,jt:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:
null,url:b1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url}),O4:za,N4:h.signin_title?h.signin_title:void 0,M4:h.signin_message?h.signin_message:void 0,offers:ha};p1(c,f);break;case "simple":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,og:m,ak:I.card?g.du(I.card):null,Nh:I.teaser?g.du(I.teaser):null,Td:I.icon?
g.du(I.icon):null,imageUrl:h.image_url,displayDomain:h.display_domain?h.display_domain:null,showLinkIcon:!!h.show_link_icon,jt:h.button_icon_url?h.button_icon_url:null,title:h.title,customMessage:h.custom_message?h.custom_message:null,url:b1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})};p1(c,f);break;case "video":f={id:f.id,timestamp:h.timestamp||0,type:h.card_type,teaserText:h.teaser_text,teaserDurationMs:h.teaser_duration_ms,startMs:h.start_ms,autoOpen:h.auto_open||
!1,Bd:h.session_data||{},sponsored:h.sponsored||!1,og:m,ak:I.card?g.du(I.card):null,Nh:I.teaser?g.du(I.teaser):null,Td:I.icon?g.du(I.icon):null,Ps:h.image_url,videoDuration:h.video_duration||null,customMessage:h.custom_message?h.custom_message:null,title:h.title,metaInfo:h.meta_info,isLiveNow:!!h.is_live_now,url:b1({pause_on_navigation:h.pause_on_navigation,target:h.target||"new",value:h.url})},p1(c,f)}}else SDa(a.u,f);c=!0}}c&&(D0(a.player),a.hv())},yEa=function(a,b){var c=!1;
a.u||(a.u=vEa(a),g.C(a,a.u));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(TDa(a.u,e.cardRenderer),c=!0);c&&(c=a.u,d=b.headerText?g.S(b.headerText):"",g.Qe(c.Ua,d),c.N&&c.N.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.da=b.trackingParams?g.du(b.trackingParams):null,c.K=b.closeButton.infoCardIconRenderer.trackingParams?g.du(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Td=b.icon.infoCardIconRenderer.trackingParams?
g.du(b.icon.infoCardIconRenderer.trackingParams):null,D0(a.player),a.hv())},zEa=function(a,b,c,d,e){if(!a.player.S().Eb){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new FDa("openUrl","click",new DDa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.S(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new JDa(c,"branding","branding",f,d);l=oEa(a);a.B.element.appendChild(l);f=new t1(l,A1(a),f);f.Es();g.C(f,f);a.K[c]=f}},sEa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.ma()||(d.unshift(b),b=g.Ra.apply(window,d),a.W.push(g.zp(b)))}},AEa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.PN.prototype.Tp=g.ca(11,function(a,b){var c=g.sO(this.Sa());c&&c.Tp(a,b)});
var F0={},G0=null;g.Ta(I0,g.Dn);g.k=I0.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.La)this.progress=0,this.coords=this.u;else if(this.Gb())return!1;H0(this);this.startTime=a=g.A();-1==this.La&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.gv();this.qh("play");-1==this.La&&this.qh("resume");this.La=1;var b=g.Qa(this);b in F0||(F0[b]=this);oDa();pDa(this,a);return!0};
g.k.stop=function(a){H0(this);this.La=0;a&&(this.progress=1);qDa(this,this.progress);this.qh("stop");this.Zr()};
g.k.pause=function(){this.Gb()&&(H0(this),this.La=-1,this.qh("pause"))};
g.k.ca=function(){0==this.La||this.stop(!1);this.qh("destroy");I0.Dd.ca.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.ny=function(){this.qh("animate")};
g.k.qh=function(a){this.dispatchEvent(new rDa(a,this))};
g.Ta(rDa,g.Ll);g.Ta(J0,I0);J0.prototype.C=g.Ja;J0.prototype.ny=function(){this.C();J0.Dd.ny.call(this)};
J0.prototype.Zr=function(){this.C();J0.Dd.Zr.call(this)};
J0.prototype.gv=function(){this.C();J0.Dd.gv.call(this)};
g.Ta(K0,J0);K0.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.u(L0,g.B);L0.prototype.ya=function(a,b,c,d){c=(0,g.z)(c,d||this.B);a=g.kp(a,b,c);this.u.push(a);return a};
L0.prototype.Xy=function(a,b,c,d){c=(0,g.z)(c,d||this.B);a=g.tp(a,b,c);this.u.push(a);return a};
L0.prototype.Jb=function(a){g.lp(a);g.lb(this.u,a)};
L0.prototype.ca=function(){g.lp(this.u);this.u.length=0;g.B.prototype.ca.call(this)};g.u(P0,g.hO);g.k=P0.prototype;g.k.load=function(){g.hO.prototype.load.call(this);if(!Q0(this)){var a=g.sja(this.player.getVideoData());a?(a=O0(a,tDa(this)),R0(this,a,!1)):uDa(this)}};
g.k.unload=function(){R0(this,null);this.C&&(this.C.abort(),this.C=null);g.hO.prototype.unload.call(this)};
g.k.He=function(a,b){if(!Q0(this))return null;if("loadCustomEndscreenRenderer"===a){var c=O0(b,"new");R0(this,c);return!0}return null};
g.k.getOptions=function(){return Q0(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Ra=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<BEa.length;f++){var h=Math.abs(b.width-BEa[f]);if(-1===e||d>=h)e=f,d=h}d=CEa[e];this.B&&g.xg(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.u[f],
h=this.F[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Ng(e.element,Math.round(h.width*a.width),f);g.Gg(e.element,m,n);g.Bn(e.element,DEa);m=h.left+h.width/2;h=h.top+l/2;g.J(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Bn(e.element,CEa);g.J(e.element,d);(e=g.se(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.xg(e,"height",f+"px")}}}}};
g.k.yd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())Y0(this,this.endscreen.impressionUrls),(a=g.ju())&&this.endscreen.visualElement&&g.qu(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.u[a],c=this.F[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");Y0(this,c.impressionUrls);(b=g.ju())&&g.qu(b,c.visualElement,void 0);this.player.S().C&&this.player.va("endscreenelementshown",
a)}};
g.k.qf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.u[a];g.An(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.An(b,"ytp-ce-shown");this.player.S().C&&this.player.va("endscreenelementhidden",a)}};
g.k.pQ=function(a){var b=this;a.target===window&&(new g.E(function(){for(var c=g.q(Object.values(b.u)),d=c.next();!d.done;d=c.next())g.Bn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.k.Yz=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})};
var BEa=[346,426,470,506,570,640,853,1280,1920],CEa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),DEa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var EDa={qV:"current",K_:"new"};var GDa={CLOSE:"close",V_:"openUrl",FI:"subscribe"},HDa={mT:"click",CLOSE:"close",LW:"hidden",o1:"rollOut",q1:"rollOver",V1:"shown"};var xEa={IS:"anchored",kI:"branding",CHANNEL:"channel",oV:"cta",OW:"highlightText",LX:"label",PLAYLIST:"playlist",M0:"popup",g2:"speech",FI:"subscribe",z2:"title",VIDEO:"video",I3:"website"},wEa={kI:"branding",bT:"card",EV:"drawer",NW:"highlight",jZ:"marker",U0:"promotion",TEXT:"text",O3:"widget"};g.u(h1,g.B);g.k=h1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.uG(a,b,{id:c});a.namespace="annotations_module";d&&this.wa.set(a,d);e&&this.Aa.set(a,e);this.context.J.Jd([a])};
g.k.Es=function(){this.context.B.subscribe("resize",this.lt,this)};
g.k.kz=function(a,b,c,d,e,f){if(this.Ia)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Me(this.element)};
g.k.lt=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=a1(a);if(f){var h=QDa(f,a.target),l=function(){a.u&&e.context.J.pauseVideo();var m=e.context.videoData.F||!1,n=g.gq(f||"");m&&n&&(n.v||n.list)?e.context.J.Ki(n.v,b,n.list,!1):g.EK(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);x1(this.context.logger,c,l,d);PDa(f)||(c=g.ju(),d=b.itct,c&&d&&g.Au(c,g.du(d)))}};
g.k.ca=function(){this.wa.clear();this.Aa.clear();g.B.prototype.ca.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.C(this,a);return a.element};g.u(m1,h1);g.k=m1.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Og(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.lt=function(){var a=this.isAvailable();g.Pg(this.element,a);g.K(this.context.J.getRootNode(),g.nT.IV_DRAWER_ENABLED,a);D0(this.J)};
g.k.destroy=function(){this.J.Tp(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.Ro(this.W);g.lp(this.ka);this.la&&this.la.dispose();this.F&&this.F.dispose();h1.prototype.destroy.call(this)};
g.k.gJ=function(){if(this.C){x1(this.context.logger,r1(this).og.close);var a=g.ju();a&&this.K&&g.Au(a,this.K);l1(this)}};
g.k.rJ=function(){g.K(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.QK=function(){var a=g.ju(),b=r1(this);b=b?b.Td:this.Td;a&&b&&g.yu(a,[b])};
g.k.PK=function(){var a=g.ju(),b=r1(this);b=b?b.Td:this.Td;a&&b&&g.zu(a,[b])};
g.k.NL=function(){var a=r1(this);x1(this.context.logger,a.og.wH);var b=g.ju();b&&a&&g.yu(b,[a.Nh,a.Td])};
g.k.SK=function(){var a=g.ju(),b=r1(this);a&&b&&g.zu(a,[b.Nh])};
g.k.ML=function(a){var b=r1(this),c=g.ju();this.u?a?(a=this.context.logger,x1(a,b.og.Rv),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Nh&&g.Au(c,b.Nh)):(a=this.context.logger,x1(a,b.og.Rv),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Td&&g.Au(c,b.Td)):(a=this.context.logger,x1(a,b.og.Rv),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.Td&&g.Au(c,this.Td))};g.u(s1,h1);s1.prototype.Es=function(){h1.prototype.Es.call(this);dEa(this)};
s1.prototype.show=function(){h1.prototype.show.call(this);var a=g.ju(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.yu(a,[g.du(b.itct)])};
s1.prototype.hide=function(){h1.prototype.hide.call(this);var a=g.ju(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.zu(a,[g.du(b.itct)])};g.u(t1,s1);
t1.prototype.show=function(){if(!this.isActive){s1.prototype.show.call(this);if(!this.K){g.J(this.element,"iv-branding");var a=this.annotation.data;this.B=this.createElement({G:"img",ia:["branding-img","iv-click-target"],T:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Pg(this.B,!1);var b=this.createElement({G:"div",ia:["branding-img-container"]});b.appendChild(this.B);this.element.appendChild(b);(b=LDa(this.annotation))&&i1(this,this.B,b,this.annotation.id,
a.session_data);hEa(this,a);this.K=!0}g.Pg(this.element,!0);this.isActive=!0;this.B&&eEa(this,this.B)}};
t1.prototype.hide=function(){this.isActive&&(s1.prototype.hide.call(this),g.Pg(this.element,!1),this.isActive=!1)};
t1.prototype.destroy=function(){this.u&&(this.u.dispose(),this.u=null);s1.prototype.destroy.call(this)};g.u(u1,s1);g.k=u1.prototype;g.k.show=function(){this.isActive||(s1.prototype.show.call(this),this.U||(jEa(this),this.U=!0),g.Pg(this.element,!0),g.Sm(function(){g.An(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,w1(this),kEa(this),lEa(this,this.I))};
g.k.hide=function(){this.isActive&&(g.J(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.kz=function(a,b,c,d,e,f){return this.isCollapsed?!1:s1.prototype.kz.call(this,a,b,c,d,e,f)};
g.k.hK=function(a){this.N=!0;v1(this,500,a)};
g.k.gK=function(){this.N=!1;mEa(this)};
g.k.aK=function(a){a.stopPropagation();this.hide()};
g.k.bK=function(a){a.stopPropagation();w1(this);this.isCollapsed=!0;g.J(this.element,"iv-promo-collapsed-no-delay");this.F.start()};
g.k.destroy=function(){this.F.dispose();s1.prototype.destroy.call(this)};g.u(y1,g.hO);g.k=y1.prototype;g.k.He=function(a,b){if(!AEa(this.player.S().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.o_(b);c&&z1(this,c);return!0;case "removeCustomAnnotationById":return b&&this.u&&(VDa(this.u,b),D0(this.player)),!0}return null};
g.k.getOptions=function(){return AEa(this.player.S().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Un=function(){var a=this.player.S(),b=this.player.getVideoData();return b.F&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.ZD||a.N.get(b.videoId)||g.eJ(b)||g.fJ(b)?!0:!1};
g.k.hv=function(){if(this.D){var a=this.player.Ja().getVideoContentRect(!0);g.Ng(this.D.element,a.width,a.height);g.Gg(this.D.element,a.left,a.top)}if(this.u){var b=this.player.jj();a=this.u;b=b.width;g.K(a.D,"iv-drawer-small",426>=b);g.K(a.D,"iv-drawer-big",1280<=b)}};
g.k.LL=function(a){pEa(this,a.state);g.T(a.state,2)&&(this.Lg()&&this.Ti()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Tp(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.I=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.sq(h)&&h.responseXML?h.responseXML:null)&&(z1(b,h),g.J(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.hO.prototype.load.call(this);pEa(this,this.player.Va());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.Bp()&&(a=sEa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.I=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.S().N.get(d);f&&tEa(e,f);f=f&&(f.qt||f.zq);if(!c.Sk||f)c.da?qEa(this,c.da,e):(this.C=function(){b.Pa(e)},this.player.addEventListener("videodatachange",this.C));
g.WN(this.player,this.D.element,4);this.hv();(f=g.eJ(c))&&yEa(this,f);(f=g.fJ(c))&&f.featuredChannel&&zEa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.Pa=function(a){var b=this.player.getVideoData();b.da&&(this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null),qEa(this,b.da,a))};
g.k.unload=function(){this.player.Re("annotations_module");for(var a=g.q(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.N=null;this.u&&(this.u.destroy(),this.u=null,D0(this.player));this.U=!1;this.I&&(this.I.abort(),this.I=null);this.K={};this.B.hide();g.hO.prototype.unload.call(this);this.D.detach();this.C&&(this.player.removeEventListener("videodatachange",this.C),this.C=null)};
g.k.pG=function(a){a===this.player.getVideoData().videoId&&(this.loaded?uEa(this):this.load())};
g.k.Lg=function(){return!!this.u&&this.u.isAvailable()};
g.k.Ti=function(){this.Lg();return!!this.u&&this.u.C};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Lg();this.u&&(a?c?k1(this.u,c,b):k1(this.u,"YOUTUBE_DRAWER_AUTO_OPEN",b):l1(this.u))};
g.k.Tp=function(a,b){this.player.V(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ca=function(){this.player.S().N.unsubscribe("vast_info_card_add",this.pG,this);g.An(this.player.getRootNode(),g.nT.IV_DRAWER_OPEN);for(var a=this.W,b=0,c=a.length;b<c;b++)g.Cp(a[b]);this.W.length=0;g.hO.prototype.ca.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.C(this,a);return a.element};g.nO.annotations_module=y1;g.nO.creatorendscreen=P0;})(_yt_player);
