(function(g){var window=this;var E1=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.UH(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.u,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},F1=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},EEa=function(a,b){var c=new g.TH;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.u=a.u;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},FEa=function(){this.B=[];
this.u=[]},G1=function(a,b){return b?a.u.concat(a.B):a.u},H1=function(a,b){switch(b.kind){case "asr":GEa(b,a.B);
break;default:GEa(b,a.u)}},GEa=function(a,b){g.cb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},I1=function(){g.B.call(this);
this.B=new FEa;this.F=[]},J1=function(a,b,c){I1.call(this,a);
this.audioTrack=c;this.u=null;this.F=b.iE},K1=function(){this.segments=[]},HEa=function(a,b){var c=g.vb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.kb(a.segments,c),g.kb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.sb(a.segments,c,0,b),g.sb(a.segments,c+1,0,b)))},L1=function(a,b,c,d,e,f){g.B.call(this);
this.policy=a;this.player=b;this.W=c;this.I=d;this.F=e;this.N=f;this.U=this.player.S();this.D=new K1;this.B=this.C=this.u=null;this.K=new g.E(this.kE,1E3,this);this.events=new g.YN(this);g.C(this,this.K);g.C(this,this.events);this.events.P(b,"SEEK_COMPLETE",this.NE);this.NE();this.kE()},IEa=function(a,b){var c=g.Kx(g.Qx(b,a.policy,{})),d={format:"RAW",
withCredentials:!0};a.F&&(d.responseType="arraybuffer");a.B=g.pt(c,d,3,100).then(function(e){a:{a.ma();if(a.C){var f=!(a.F?e.response:e.responseText)||400<=e.status,h=g.RB(e);if(h){e=g.Qx(a.C,a.policy,{});f=a.C;g.Dy(f.B,e,h);f.requestId=e.get("req_id");IEa(a,a.C);break a}f||null==a.I||(h=a.C.u[0],a.F?a.I(e.response,1E3*(h.startTime+a.player.Ac())):a.I(e.responseText,1E3*(h.startTime+a.player.Ac())))}a.C=null;a.B=null}});
a.C=b;HEa(a.D,a.C.u[0].xa)},M1=function(a,b){I1.call(this,b.S());
this.u=a;this.J=b;this.C=null;this.D=!1;this.I=g.VD(this.J.S())&&!this.u.isManifestless},JEa=function(a,b){var c=[],d;
for(d in a.u.u)if(a.u.u.hasOwnProperty(d)){var e=a.u.u[d];if(g.iO(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.TH({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},KEa=function(a,b){return null!=b&&b in a.u.u?a.u.u[b]:null},LEa=function(a,b,c){var d=[],e;
for(e in a.u.u)if(a.u.u.hasOwnProperty(e)){var f=a.u.u[e];if(g.iO(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},N1=function(a,b,c,d,e){I1.call(this,e||null);
this.videoId=b;this.ID=d;this.D={};this.u=null;b=c||g.gq(a).hl||"";b=b.split("_").join("-");this.C=g.iq(a,{hl:b})},O1=function(a,b,c,d,e,f,h){var l={};
g.Sa(l,b);g.Sa(l,a.params);g.Sa(l,c);var m={};g.Sa(m,b.Hc);a.params.Hc&&g.Sa(m,a.params.Hc);g.Sa(m,c.Hc);l.Hc=m;g.U.call(this,{G:"div",L:"caption-window",T:{id:"caption-window-"+a.id,dir:1===l.Ve?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},R:[{G:"span",L:"captions-text",T:{style:"word-wrap: normal; display: block;"}}]});this.F=[];this.Z=!1;this.B=a;this.ga=this.da=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.I=null;this.maxWidth=.96*e;this.Ia=.96*f;this.u=
l;this.ob=c;this.D=this.ha("captions-text");this.Ua=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.ea=d/360*16;this.type=0;this.wa=this.ea*MEa(m);a=new g.Ut(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.TL,this);a.subscribe("dragmove",this.SL,this);a.subscribe("dragend",this.RL,this);this.Ga=this.Aa=0;b="";this.u.windowOpacity&&(a=g.n_(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+
")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":NEa[this.u.textAlign]};this.Ua&&(a["border-radius"]=b?this.wa/8+"px":"");if(this.C=2===this.B.params.Ve||3===this.B.params.Ve)b=this.element,c="vertical-rl",1===this.u.CA&&(c="vertical-lr"),g.ze&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.xg(b,"-o-writing-mode",c),g.xg(b,"-webkit-writing-mode",c),g.xg(b,"writing-mode",c),g.xg(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3===this.B.params.Ve&&(g.xg(b,"text-orientation",
""),g.xg(b,"transform","rotate(180deg)"));g.xg(this.element,a);switch(this.u.Uh){case 0:case 1:case 2:g.J(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},MEa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},OEa=function(a,b){var c={},d=b.background?b.background:a.u.Hc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.Hc.backgroundOpacity;d=g.n_(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ua&&(c["box-decoration-break"]="clone",c["border-radius"]=a.wa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ea*MEa(b)+"px";d=1;e=b.color||a.u.Hc.color;if(b.color||null!=b.textOpacity)e=g.n_(e),d=null==b.textOpacity?a.u.Hc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.lx&&(h=e=b.lx);var l=a.ea/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.$q()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.Hc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.gi&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.yK&&(c.visibility="hidden");1===b.DD&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.$D||g.Zr,3===a.B.params.Ve?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Ei||2===b.Ei||3===b.Ei||4===b.Ei||5===b.Ei)if(g.$D)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Ei){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},PEa=function(a){a.I=g.Ge("SPAN");
g.xg(a.I,{display:"block"});g.J(a.I,"caption-visual-line");a.D.appendChild(a.I)},QEa=function(a,b){var c=g.Ge("SPAN");
g.xg(c,{display:"inline-block","white-space":"pre-wrap"});g.xg(c,OEa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.xg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.xg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},REa=function(a,b,c){a.Z=a.Z||!!c;
var d={};g.Sa(d,a.u.Hc);g.Sa(d,c||b.u);g.Sa(d,a.ob.Hc);(c=!a.I)&&PEa(a);for(var e=a.da&&a.ga&&g.Tb(d,a.ga)?a.da:QEa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(PEa(a),e=QEa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.He(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.$D||!g.Cg(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Cg(n.children[2],"text-emphasis-position")&&(m=a.C?"padding-left":"padding-bottom"),
g.Be?g.xg(e,m,"1em"):g.xg(e,m,"0.5em")))}a.ga=d;a.da=e;a.F.push(b)},P1=function(a,b,c,d,e,f,h){O1.call(this,a,b,c,d,e,f,h);
this.type=1},Q1=function(a,b,c,d,e,f,h){O1.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.W=this.N=this.ka=0;this.X=NaN;this.Oa=0;this.Xa=null;this.la=new g.E(this.wP,433,this);g.J(this.element,"ytp-caption-window-rollup");g.C(this,this.la);g.xg(this.element,"overflow","hidden")},SEa=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.CA&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},TEa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Lk,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.N=d;b=Math;c=b.max;isNaN(a.X)&&((d=a.u.kl)?(e=g.Ge("SPAN"),g.Qe(e,"\u2013".repeat(d)),g.xg(e,OEa(a,a.u.Hc)),a.D.appendChild(e),a.X=e.offsetWidth,a.D.removeChild(e)):a.X=0);d=a.D;a.W=c.call(b,a.X,a.Oa,(a.C?d.offsetHeight:d.offsetWidth)+1)},UEa=function(a,b){TEa(a);
var c=a.K.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.N-c;if(c!==a.ka){var d=0<c&&0===a.ka;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.sn(a.la));g.xg(a.D,"transform",SEa(a,c));a.ka=c}TEa(a)},R1=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.uG.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.u=h},S1=function(a,b,c,d,e){g.uG.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.u=[]},VEa=function(a){var b="_"+T1++;
return new S1(0,0x8000000000000,0,b,a)},XEa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Ad){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=WEa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new R1(a,b,e,c,l,d,m)}switch(m.Ad){case 9:case 10:m.Ei=1;break;case 11:m.Ei=2;break;case 12:m.Ei=3;break;case 13:m.Ei=4;break;case 14:m.Ei=5}return new R1(a,b,e,c,l.textContent||"",d,m)},WEa=function(a,b,c,d,e){var f=g.$q(),h=
f?g.Ge("DIV"):g.Ge("RUBY"),l=g.Ge("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ge("DIV"):g.Ge("RP");a.textContent=b;h.appendChild(a);b=f?g.Ge("DIV"):g.Ge("RT");b.textContent=c;h.appendChild(b);c=e.Ad;if(10===c||11===c||12===c||13===c||14===c)if(g.xg(b,"text-emphasis-style","filled circle"),g.xg(b,"text-emphasis-color","currentcolor"),g.xg(b,"webkit-text-emphasis","filled circle"),11===e.Ad||13===e.Ad)g.xg(b,"webkit-text-emphasis-position","under left"),g.xg(b,"text-emphasis-position","under left");c=!0;if(4===e.Ad||7===e.Ad||12===e.Ad||
14===e.Ad)g.xg(h,"ruby-position","over"),g.xg(h,"-webkit-ruby-position","before");else if(5===e.Ad||6===e.Ad||11===e.Ad||13===e.Ad)g.xg(h,"ruby-position","under"),g.xg(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ge("DIV"):g.Ge("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.xg(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.xg(f,"display","none"),f=f.nextElementSibling,g.xg(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.xg(h.lastElementChild,"display","none"),d?(g.xg(h,"padding-top","0.6em"),g.xg(f,"top","0")):(g.xg(h,"padding-bottom","0.6em"),g.xg(f,"bottom","0")));return h},U1=function(){g.B.apply(this,arguments)},V1=function(a){U1.call(this);
this.I=a;this.D={};this.U={};this.W={};this.F="_"+T1++;this.N={};this.B=this.u=null;this.K=!0},W1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},X1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},Y1=function(a,b){var c=W1(a,b);
return void 0!==c?c:null},$1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Z1.test(c),c},YEa=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.W[d]:a.I);d=Y1(b,"mh");null!=d&&(c.qp=d);d=Y1(b,"ju");null!=d&&(c.textAlign=d);d=Y1(b,"pd");null!=d&&(c.Ve=d);d=Y1(b,"sd");null!=d&&(c.CA=d);d=$1(b,"wfc");null!=d&&(c.windowColor=d);d=W1(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},ZEa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.U[d]);d=Y1(b,"ap");null!=d&&(c.Uh=d);d=W1(b,"cc");null!=d&&(c.kl=d);d=W1(b,"ah");null!=d&&(c.Vg=d);d=W1(b,"rc");null!=d&&(c.Lk=d);d=W1(b,"av");null!=d&&(c.Gi=d);return c},$Ea=function(a,b,c,d){var e={};
g.Sa(e,ZEa(a,b));g.Sa(e,YEa(a,b));d?g.Tb(e,a.I)?(d=a.F,e=a.I):d="_"+T1++:d=b.getAttribute("id")||"_"+T1++;a=W1(b,"t")+c;b=W1(b,"d")||0x8000000000000;if(2===e.Ve||3===e.Ve)c=e.Lk,e.Lk=e.kl,e.kl=c;return new S1(a,b,0,d,e)},a2=function(a){U1.call(this);
this.I=a;this.u=new Map;this.D=new Map;this.F=new Map;this.B=new Map},b2=function(a){a=g.ee(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},aFa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.D.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.F.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Lk=a);b=b.ccColCount;void 0!==b&&(f.kl=b);if(2===f.Ve||3===f.Ve)b=f.Lk,f.Lk=f.kl,f.kl=b;return new S1(c,d,0,e,f)},d2=function(){this.C=this.time=this.mode=this.B=0;
this.D=new c2(this);this.F=new c2(this);this.u=[];this.clear()},cFa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Vm:a,
dl:b,result:0};a=bFa[a];b=bFa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.dl===d;if(d)return{Vm:a,dl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Vm:a,dl:b,result:2};return{Vm:a,dl:b,result:3}},eFa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.u.clear(),a.F.u.clear()):(a.C=0,dFa(a.D,b,c,d))},fFa=function(a,b){a.u.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.u),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?eFa(a,d.cC,d.dC,b):1===d.type&&a.B&496&&dFa(a.F,d.cC,d.dC,b);a.u.length=0},e2=function(){this.type=0},f2=function(){this.state=this.dl=this.Vm=0},gFa=function(){this.timestamp=this.u=0},g2=function(a){this.F=a;
this.C=[];this.u=this.B=this.row=0;this.style=new e2;for(a=this.D=0;15>=a;a++){this.C[a]=[];for(var b=0;32>=b;b++)this.C[a][b]=new gFa}},h2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.F.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.C[m][p];
if(0!==r.u){0===c&&(c=m,d=p);n=String.fromCharCode(r.u);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.u||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.F.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.C[h][m],r=p.u,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},lFa=function(a,b){switch(a){case 0:return hFa[(b&127)-32];
case 1:return iFa[b&15];case 2:return jFa[b&31];case 3:return kFa[b&31]}return 0},i2=function(a){return a.C[a.row][a.B]},j2=function(a,b,c){2<=b&&1<a.B&&(--a.B,i2(a).u=0);
var d=i2(a);d.timestamp=a.F.time+0;d.u=lFa(b,c);32>a.B&&a.B++},mFa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.C[b+e][f],l=a.C[c+e][f];
h.u=l.u;h.timestamp=l.timestamp}},k2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.C[b+d][e].reset()},l2=function(a){a.row=0<a.u?a.u:1;
a.B=1;k2(a,0,15)},m2=function(a){this.C=a;
this.F=0;this.style=new e2;this.I=new g2(this.C);this.K=new g2(this.C);this.text=new g2(this.C);this.B=this.I;this.D=this.K;this.u=this.B},n2=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.u||(h2(d,c),l2(a.B),l2(a.D),d.row=15,d.u=b,e=!0)}a.style.set(3);a.u=d;a.u.style=a.style;a.C.mode=1<<d.D;e?d.B=1:d.u!==b&&(d.u>b?(h2(d,c),k2(d,d.row-d.u,b)):d.row<b&&(b=d.u),d.u=b)},nFa=function(a){a.style.set(1);
a.u=a.D;a.u.u=0;a.u.style=a.style;a.C.mode=1<<a.u.D},oFa=function(a){a.style.set(4);
a.u=a.text;a.u.style=a.style;a.C.mode=1<<a.u.D},c2=function(a){this.B=a;
this.F=0;this.C=new m2(this.B);this.I=new m2(this.B);this.u=new f2;this.D=this.C},dFa=function(a,b,c,d){a.u.update();
b=cFa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Vm;c=b.dl;if(32<=e||!e)a.B.mode&a.B.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.u,b&96&&j2(a,0,b),c&96&&j2(a,0,c),0!==b&&0!==c&&3===a.style.type&&h2(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Vm=e,b.dl=c,b.state=2,b=e&8?a.I:a.C,a.D=b,a.B.mode=1<<(a.F<<2)+(b.F<<1)+(4===b.style.type?1:0),(a.B.mode|1<<(a.F<<2)+(b.F<<1)+(4!==b.style.type?1:0))&a.B.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.u;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.u&&(d=c.u,d===c.row))break;var f=1+c.row-c.u,h=1+d-c.u;mFa(c,h,f,c.u);b=f;e=c.u;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));k2(c,b,e)}}c.row=d;c.B=a+1}else switch(e&7){case 1:switch(c&112){case 32:j2(b.u,0,32);break a;case 48:57===c?(d=b.u,i2(d).u=0,32>d.B&&d.B++):j2(b.u,1,c&15)}break;case 2:c&32&&j2(b.u,2,c&31);break;case 3:c&32&&j2(b.u,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:nFa(b);
break;case 33:d=b.u;1<d.B&&(--d.B,i2(d).u=0);break;case 36:d=b.u;b=i2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.C[a][c]===b){for(;32>=c;c++)d.C[a][c].reset();break}break;case 37:n2(b,2,d);break;case 38:n2(b,3,d);break;case 39:n2(b,4,d);break;case 40:j2(b.u,0,32);break;case 41:b.style.set(2);b.u=b.B;b.u.u=0;b.u.style=b.style;b.C.mode=1<<b.u.D;break;case 42:d=b.text;d.u=15;d.style.set(4);l2(d);oFa(b);break;case 43:oFa(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:h2(a,d)}k2(a,
0,15);break;case 45:b:{a=b.u;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.B=1;break b}case 3:}2>a.u&&(a.u=2,a.row<a.u&&(a.row=a.u));b=a.row-a.u+1;h2(a,d);mFa(a,b,b+1,a.u-1);k2(a,a.row,1)}break;case 46:k2(b.D,0,15);break;case 47:h2(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,nFa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.u,32<(d.B+=c&3)&&(d.B=32)}}},pFa=function(){},o2=function(a,b,c){this.K=a;
this.I=c;this.version=this.F=this.C=this.byteOffset=0;this.u=new DataView(this.K);this.B=[]},p2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.u.getUint8(b)},q2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.u.getUint32(b)},r2=function(a,b){U1.call(this);
this.B=a;this.D=b;this.track="CC3"===this.D.languageName?4:0;this.u=new d2;this.u.B=1<<this.track},s2=function(a){if("string"===typeof a)return!1;
a=new o2(a,8,0);return qFa(a)},qFa=function(a){if(!(a.byteOffset<a.u.byteLength)||1380139777!==q2(a))return!1;
a.version=p2(a);if(1<a.version)return!1;p2(a);p2(a);p2(a);return!0},t2=function(){U1.call(this)},rFa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.gi=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new R1(b,c,d,e.id,p.nodeValue,f||0<n,g.Qb(l)?void 0:l),m.push(p),e.u.push(p);else{var r={};g.Sa(r,l);rFa(a,b,c,d,e,!0,p,r,m)}}},u2=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},sFa=function(a,b,c,d){d=Object.assign({qp:0},d);
return new S1(a,b,c,"_"+T1++,d)},v2=function(a){g.B.call(this);
this.B=a;this.u=null},uFa=function(a){var b={};
if(a=F1(a))b.lang=a,tFa.test(a)&&(b.Ve=1);return b},y2=function(a){g.hO.call(this,a);
var b=this;this.J=a;this.B=this.J.S();this.videoData=this.J.getVideoData();this.Oa=this.J.Ja();this.D={Hc:{}};this.F={Hc:{}};this.W=[];this.U={};this.la={};this.da=!1;this.Ga=g.mpa(this.videoData,this.J);this.Ua=!!this.videoData.captionTracks.length;this.Xa=!!this.videoData.ih;this.Ha="3"===this.B.controlsType;this.C=this.K=this.N=this.ka=this.Aa=null;this.wa=new v2(this.B);this.u=null;this.ga=new g.YN(this);var c=null,d=g.po("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Zn(d));this.storage=
c;c=a.fd();d=!(!c||!c.Ms());this.Ia=!(!c||!c.Ns());this.I=this.Ha&&d&&!this.Ga;this.Z=!this.I&&this.Ha&&this.Ia&&this.Ga;g.C(this,this.wa);this.I?this.ea=this.X=null:(this.X=new g.on(this.KH,void 0,this),g.C(this,this.X),this.ea=new g.E(this.RQ,2E3,this),g.C(this,this.ea));g.C(this,this.ga);this.I||this.ga.P(a,"resize",this.UA);this.ga.P(a,"onPlaybackAudioChange",this.FN);this.ga.P(a,g.xG("captions"),function(e){b.yd(e)});
this.ga.P(a,g.yG("captions"),function(e){b.qf(e)});
w2(this,x2(this,"display-settings")||{})},vFa=function(a){if(1===a.B.Ia||1===a.videoData.ww||"alwayson"===g.YI(a.videoData,"yt:cc"))return!0;
if(2===a.B.Ia){var b;g.ZD(a.B)?b=(0,g.zCa)():b=x2(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().C;return"ON"===c||"on"===g.YI(a.videoData,"yt:cc")},z2=function(a,b){if(a.u&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.B||"FORCED_ON"===c.C},wFa=function(a){var b=!1,c=g.Gt(g.Et.getInstance(),65);
if(g.ZD(a.B)&&null!=c){if(null!=(0,g.zCa)())return!1;b=!c}return b},B2=function(a,b){if(a.C){if(a.K&&a.K.F)return a.K.F;
var c=b;c||(c=a.Xa?!1:a.Ua?!1:!0);c=G1(a.C.B,c);for(var d=[a.videoData.captionsLanguagePreference,a.B.captionsLanguagePreference,g.YI(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(F1(c[f])===d[e])return c[f];return a.K&&a.K.D?a.K.D:(d=c.find(function(h){return h.isDefault}))?d:c[0]||A2(a)}return null},A2=function(a){return a.K&&a.K.B},C2=function(a){var b=A2(a);
return!!b&&a.u===b},xFa=function(a,b){for(var c=a.J.fd().Xd().textTracks,d=a.u.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},E2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.da=c,a.da&&(g.ZD(a.B)?(0,g.N_)(!!b):D2(a,"module-enabled",!!b)));a.u=b;z2(a)&&(a.u=A2(a));a.load()},yFa=function(a,b){var c=a.Oa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.u?a.u.languageCode:null;!b.params.Ve&&d&&tFa.test(d)&&(b.params.Ve=1);d=a.Oa.getPlayerSize();switch(null!=b.params.qp?b.params.qp:1<b.u.length?1:0){case 1:return new P1(b,a.D,a.F,c,d.width,d.height,a.B.experiments);case 2:return new Q1(b,a.D,a.F,c,d.width,d.height,a.B.experiments);default:return new O1(b,a.D,a.F,c,d.width,d.height,a.B.experiments)}},w2=function(a,b,c){c=void 0===c?!1:c;
var d=F2.Hc;a.D={};g.Sa(a.D,F2);a.D.Hc={};g.Sa(a.D.Hc,d);a.F={Hc:{}};var e=b.backgroundOverride?a.F:a.D,f=b.background||d.background;Z1.test(f);e.Hc.background=f;e=b.colorOverride?a.F:a.D;f=b.color||d.color;Z1.test(f);e.Hc.color=f;e=b.windowColorOverride?a.F:a.D;f=b.windowColor||F2.windowColor;Z1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.D;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Hc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.D;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Hc.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.D;e=b.fontStyle;null==e&&(e=d.bold&&d.gi?3:d.bold?1:d.gi?2:0);f=f.Hc;switch(e){case 1:f.bold=!0;delete f.gi;break;case 2:delete f.bold;f.gi=!0;break;case 3:f.bold=!0;f.gi=!0;break;default:delete f.bold,delete f.gi}e=b.textOpacityOverride?a.F:a.D;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Hc.textOpacity=f;e=b.windowOpacityOverride?a.F:a.D;f=b.windowOpacity;null==f&&(f=F2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.D;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Hc.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Hc.fontFamily=f;a.loaded&&a.UA();c&&D2(a,"display-settings",b)},AFa=function(a,b){if(b&&!a.N){var c=VEa({Ve:0,
lang:"en-GB"});a.N=[c,new R1(c.start,c.end-c.start,0,c.id,"Captions look like this")];a.player.Jd(a.N)}else!b&&a.N&&(zFa(a,a.N),a.N=null)},zFa=function(a,b){a.player.kg(b);
g.Bb(b,function(c){g.lb(this.W,c)},a);
g.pn(a.X)},x2=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},D2=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.vO.prototype.Bq=g.ca(19,function(){this.aa();for(var a=g.se(document,"track",void 0,this.u),b=0;b<a.length;b++)g.Me(a[b])});
g.xS.prototype.Bq=g.ca(18,function(){this.u.Bq()});
g.vO.prototype.Ns=g.ca(17,function(){return!(!this.u.textTracks||!this.u.textTracks.addEventListener)});
g.xS.prototype.Ns=g.ca(16,function(){return this.u.Ns()});
g.vO.prototype.Ms=g.ca(15,function(){return!!this.u.textTracks});
g.xS.prototype.Ms=g.ca(14,function(){return this.u.Ms()});
g.vO.prototype.qq=g.ca(13,function(a){this.aa();for(var b=0;b<a.length;b++)this.u.appendChild(a[b])});
g.xS.prototype.qq=g.ca(12,function(a){this.u.qq(a)});
g.Gy.prototype.Xt=g.ca(1,function(){return 0});
g.eA.prototype.Xt=g.ca(0,function(a){return(a=this.Wh(a))?a.u:0});
var tFa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;g.u(I1,g.B);g.k=I1.prototype;g.k.vu=function(){};
g.k.wu=function(){};
g.k.Tk=function(){};
g.k.Vo=function(){return""};
g.k.CG=function(){return!1};
g.k.ca=function(){this.Tk();g.B.prototype.ca.call(this)};
g.u(J1,I1);J1.prototype.vu=function(a,b,c){var d=this;this.ma();b=this.Vo(a,b);this.Tk();this.u=g.yq(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
J1.prototype.wu=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())H1(this.B,c.value);a()};
J1.prototype.Vo=function(a,b){var c=a.url,d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.$q()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=F1(a));return g.iq(c,d)};
J1.prototype.Tk=function(){this.u&&this.u.abort()};
K1.prototype.contains=function(a){a=g.vb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
K1.prototype.length=function(){return this.segments.length/2};
g.u(L1,g.B);g.k=L1.prototype;g.k.ca=function(){g.B.prototype.ca.call(this);this.B&&this.B.cancel()};
g.k.NE=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Ac();var b=this.u;this.u=g.ab(this.W.Bl(a).u);b!==this.u&&this.N&&this.N()};
g.k.reset=function(){this.D=new K1;this.B&&(this.B.cancel(),this.B=null)};
g.k.kE=function(){this.ma();var a;if(a=null!=this.u)a=this.u,a=a.u.Sl(a);!a||this.B||this.u&&30<this.u.startTime-this.player.getCurrentTime()||(a=this.u,a=a.u.Mr(a),a.u[0].duration?(this.D.contains(a.u[0].xa)||IEa(this,a),this.u=g.ab(a.u)):!g.P(this.U.experiments,"force_caption_seek_for_live_killswitch")&&this.u&&this.u.D&&this.u.D+this.player.Ac()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.K.start()};
g.u(M1,I1);g.k=M1.prototype;g.k.vu=function(a,b,c){var d=this;this.Tk();b=KEa(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?LEa(this,b,"386"):LEa(this,b));if(b){var e=1E3*(b.index.Xt(b.index.Zh())-b.index.jf(b.index.Zh()));this.C=new L1(new g.yy,this.J,b,function(f,h){c(f,a,h,e)},this.I||g.tw(b.info),function(){d.C&&d.C.reset();
d.D=!0})}};
g.k.CG=function(){var a=this.D;this.D=!1;return a};
g.k.wu=function(a){var b=this.I?[new g.TH({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.TH({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?JEa(this,"386"):JEa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())H1(this.B,c.value);a()};
g.k.Tk=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Vo=function(){return""};
g.u(N1,I1);N1.prototype.vu=function(a,b,c){var d=this;this.ma();b=this.Vo(a,b);this.Tk();this.u=g.yq(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
N1.prototype.wu=function(a){var b=this,c=this.C,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.ID&&(d.asrs=1);c=g.iq(c,d);this.Tk();this.u=g.yq(c,{format:"RAW",onSuccess:function(e){b.u=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");H1(b.B,new g.TH({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.D[m.languageCode]=m.languageName,b.F.push(m)}a()},
withCredentials:!0})};
N1.prototype.Vo=function(a,b){var c=this.C,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=F1(a));return c=g.iq(c,d)};
N1.prototype.Tk=function(){this.u&&this.u.abort()};
var Z1=/^#(?:[0-9a-f]{3}){1,2}$/i;var NEa=["left","right","center","justify"];g.u(O1,g.U);g.k=O1.prototype;g.k.TL=function(a,b){var c=g.Mg(this.element,this.element.parentElement);this.Aa=a-c.x;this.Ga=b-c.y;g.J(this.element,"ytp-dragging")};
g.k.SL=function(a,b){var c=g.Og(this.element),d=a-this.Aa-.02*this.playerWidth,e=b-this.Ga-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.ee(f,0,2));var h=(e+c.height/2)/this.Ia*3;h=Math.floor(g.ee(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.ee(d,0,1);c=(e+h/2*c.height)/this.Ia;c=100*g.ee(c,0,1);this.B.params.Uh=l;this.B.params.Gi=c;this.B.params.Vg=d;this.u.Uh=l;this.u.Gi=c;this.u.Vg=d;this.ZG()};
g.k.RL=function(){g.An(this.element,"ytp-dragging")};
g.k.ZG=function(){this.Wp(this.F)};
g.k.Fb=function(){return this.type};
g.k.Wp=function(a){var b=Math.min(this.bD(),this.maxWidth),c=this.aD(),d="";3===this.B.params.Ve&&(d="rotate(180deg)");g.xg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Yw(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.Vg+2;d=this.u.Uh;switch(d){case 0:case 3:case 6:b=this.u.Hc.fontSizeIncrement;!g.P(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.Ve&&3!==this.u.Ve&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.D.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.Gi+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.xg(this.element,a)};
g.k.Yw=function(a){var b;for(b=0;b<a.length&&a[b]===this.F[b];b++);if(this.Z||this.F.length>b)b=0,this.Z=!1,this.F=[],this.I=this.ga=this.da=null,g.Ie(this.D);for(;b<a.length;b++)REa(this,a[b])};
g.k.bD=function(){return 0};
g.k.aD=function(){return 0};
g.k.toString=function(){return g.U.prototype.toString.call(this)};g.u(P1,O1);P1.prototype.Yw=function(a){var b=this.B.u;O1.prototype.Yw.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.u===e)var d=f;else{d={};g.Sa(d,c.u);g.Sa(d,BFa);var e=c.u;var f=d}REa(this,c,d)}};
var BFa={yK:!0};g.u(Q1,O1);g.k=Q1.prototype;g.k.ZG=function(){g.tn(this.la)};
g.k.wP=function(){g.An(this.element,"ytp-rollup-mode");this.Wp(this.Xa,!0)};
g.k.aD=function(){return this.C?this.W:this.N};
g.k.bD=function(){return this.C?this.N:this.W};
g.k.Wp=function(a,b){this.Xa=a;if(this.B.params.Lk){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.Oa=this.W;this.N=this.W=0;O1.prototype.Wp.call(this,a);UEa(this,b)}O1.prototype.Wp.call(this,a)};g.u(R1,g.uG);R1.prototype.toString=function(){return g.uG.prototype.toString.call(this)};g.u(S1,g.uG);S1.prototype.toString=function(){return g.uG.prototype.toString.call(this)};
var T1=0;g.u(U1,g.B);U1.prototype.C=function(){return[]};
U1.prototype.reset=function(){};g.u(V1,U1);V1.prototype.reset=function(){this.N={};this.B=this.u=null;this.K=!0};
V1.prototype.C=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.D,l={},m=c.getAttribute("p");m&&g.Sa(l,this.D[m]);m=X1(c,"b");null!=m&&
(l.bold=m);m=X1(c,"i");null!=m&&(l.gi=m);m=X1(c,"u");null!=m&&(l.underline=m);m=Y1(c,"et");null!=m&&(l.charEdgeStyle=m);m=Y1(c,"of");null!=m&&(l.offset=m);m=$1(c,"bc");null!=m&&(l.background=m);m=$1(c,"ec");null!=m&&(l.lx=m);m=$1(c,"fc");null!=m&&(l.color=m);m=Y1(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=W1(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=W1(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=W1(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=Y1(c,"rb");null!=m&&10!==m&&0!==m&&(l.Ad=
10<m?m-1:m);c=Y1(c,"hg");null!=c&&(l.DD=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.W[d]=YEa(this,c);break;case "wp":d=c.getAttribute("id"),this.U[d]=ZEa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.u=$Ea(this,d,e,!1);(d=this.N[this.u.id])&&d.end>this.u.start&&(d.end=this.u.start);this.N[this.u.id]=this.u;c.push(this.u);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.F;m=!!X1(d,
"a");n=(W1(d,"t")||0)+n;var p=W1(d,"d")||5E3;m||(!this.K&&this.B&&this.B.windowId===l&&this.B.end>n&&(this.B.end=n),this.B&&"\n"===this.B.text&&(this.B.text=""));var r=m?6:5,t=d.getAttribute("p");t=t?this.D[t]:null;var w=Array.from(d.childNodes);w.length&&(this.K=null!=d.getAttribute("d"));for(var x=0;x<w.length;x++){var y=w[x],F=void 0;0<x&&(m=!0);var D=void 0;1===y.nodeType&&(D=y);if(D&&"s"===D.tagName){if((y=(y=D.getAttribute("p"))?this.D[y]:null)&&y.Ad&&(1===y.Ad?(y=w.slice(x,x+4),4===y.length&&
(F=XEa(n,p,l,m,r,y,this.D),x+=3)):F=XEa(n,p,l,m,r,[D],this.D)),!F){var G=D;F=n;D=p;y=l;var H=m,I=r,za=G.textContent?G.textContent:"",ha=G.getAttribute("p");ha=ha?this.D[ha]:null;G=W1(G,"t")||0;F=new R1(F+G,D-G,I,y,za,H,ha)}}else F=new R1(n,p,r,l,y.textContent||"",m,t);h.push(F);this.B=F}if(0<h.length)for(h[0].windowId===this.F&&(this.u=$Ea(this,d,e,!0),c.push(this.u)),d=g.q(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.u.id,this.u.u.push(h),c.push(h)}e=c}else e=[];return e};var CFa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(a2,U1);a2.prototype.reset=function(){this.B.clear()};
a2.prototype.C=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.u.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.gi=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.lx=b2(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=b2(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=b2(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.Ad=10<l?l-1:l,h.Ei=CFa.get(h.Ad));f.hgHorizGroup&&(h.DD=f.hgHorizGroup);this.u.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.F.get(l)):Object.assign(h,
this.I),void 0!==f.mhModeHint&&(h.qp=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.Ve=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.CA=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=b2(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.F.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.D.get(l)),void 0!==f.ahHorPos&&
(h.Vg=f.ahHorPos),void 0!==f.apPoint&&(h.Uh=f.apPoint),void 0!==f.avVerPos&&(h.Gi=f.avVerPos),void 0!==f.ccCols&&(h.kl=f.ccCols),void 0!==f.rcRows&&(h.Lk=f.rcRows),this.D.set(d++,h);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=aFa(this,m,e,f,h),d.push(e),this.B.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+T1++,l=aFa(this,m,e,f,h),d.push(l),this.B.set(h,l));0===f&&(f=5E3);l=this.B.get(h);var n=
!!m.aAppend,p=n?6:5,r=m.segs,t=null;m.pPenId&&(t=this.u.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],x=w.utf8;if(x){var y=w.tOffsetMs||0,F=null;w.pPenId&&(F=this.u.get(w.pPenId));if(2===(null!=l.params.qp?l.params.qp:1<l.u.length?1:0)&&n&&"\n"===x)continue;if(w=F&&1===F.Ad)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var D=r[w+1].pPenId;(D=this.u.get(D))&&D.Ad&&2===D.Ad?(D=r[w+2].pPenId,D=this.u.get(D),!D||!D.Ad||3>D.Ad?w=!1:(D=r[w+3].pPenId,w=(D=this.u.get(D))&&
D.Ad&&2===D.Ad?!0:!1)):w=!1}if(w){y=r[m+1].utf8;w=r[m+3].utf8;D=r[m+2].utf8;var G=this.u.get(r[m+2].pPenId);x=WEa(x,y,D,w,G);n=new R1(e,f,p,h,x,n,F);m+=3}else n=new R1(e+y,f-y,p,l.id,x,n,F||t);n&&(d.push(n),l.u.push(n))}n=!0}}}else d=[];return d};d2.prototype.clear=function(){this.C=this.time=this.mode=0;this.u=[];this.reset()};
d2.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var bFa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];e2.prototype.set=function(a){this.type=a};
e2.prototype.get=function(){return this.type};
f2.prototype.clear=function(){this.state=0};
f2.prototype.update=function(){this.state=2===this.state?1:0};
f2.prototype.isValid=function(){return 0!==this.state};
f2.prototype.matches=function(a,b){return this.isValid()&&a===this.Vm&&b===this.dl};
gFa.prototype.reset=function(){this.timestamp=this.u=0};
g2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.C[b][c].timestamp=a};
g2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.C[b][c];a=0===d.u?a+"_":a+String.fromCharCode(d.u)}a+="\n"}return a};
g2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.C[b][c].reset();this.D=a;this.u=0;this.B=this.row=1};
var hFa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],iFa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],jFa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],kFa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];m2.prototype.reset=function(a,b){this.F=b;this.style.set(2);this.B=this.I;this.D=this.K;this.u=this.B;var c=(a<<2)+(b<<1);this.I.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
c2.prototype.reset=function(a){this.F=a;this.u.clear();this.D=this.C;this.C.reset(a,0);this.I.reset(a,1)};pFa.prototype.D=function(){};g.u(o2,pFa);o2.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+T1++;c=c/1E3-this.I;d=d/1E3-this.I;a=new S1(c,d-c,5,f,{textAlign:0,Uh:0,Vg:2.5*b,Gi:5.33*a});e=new R1(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.u(r2,U1);r2.prototype.C=function(a){a=new o2(a,a.byteLength,this.B);if(qFa(a)){for(;a.byteOffset<a.u.byteLength;)for(0===a.version?a.C=q2(a)*(1E3/45):1===a.version&&(a.C=4294967296*q2(a)+q2(a)),a.F=p2(a);0<a.F;a.F--){var b=p2(a),c=p2(a),d=p2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.u,b.u.push({time:a.C,type:this.track,cC:c,dC:d,order:b.u.length}))}fFa(this.u,a);return a.B}return[]};
r2.prototype.reset=function(){this.u.clear()};g.u(t2,U1);
t2.prototype.C=function(a,b){for(var c=[],d=a.split(DFa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!EFa.test(f)){var l=G2.exec(f);if(l&&4<=l.length){var m=u2(l[1]),n=u2(l[2])-m;m+=h;var p=(l=l[3])?l.split(" "):[];l={};var r=null,t="",w=null,x="";l.textAlign=2;p=g.q(p);for(var y=p.next();!y.done;y=p.next())if(y=y.value.split(":"),2===y.length){var F=y[1];switch(y[0]){case "line":y=F.split(",");y[0].endsWith("%")&&(r=y[0],l.Gi=Number.parseInt(r,10),2===y.length&&(t=y[1].trim()));break;case "position":y=
F.split(",");w=y[0];l.Vg=Number.parseInt(w,10);2===y.length&&(x=y[1].trim());break;case "align":switch(F){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.Gi=100,t||(t="end"));if(!w)switch(l.textAlign){case 0:l.Vg=0;break;case 1:l.Vg=100;break;default:l.Vg=50}r=0;switch(t){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(x){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Uh=0>r||8<r?7:r;f=f.substring(G2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");x=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=sFa(m,n,5,x),n=new R1(m,n,5,h.id,l,!1,g.Qb(f)?void 0:f),c.push(h),c.push(n),h.u.push(n);else for(t=l.split(FFa),1===t.length?(l=5,x=sFa(m,n,l,x)):(r=l=6,x=Object.assign({kl:32},x),x=new S1(m,n,r,"_"+T1++,x)),c.push(x),r=m,w=0;w<t.length;w++)p=t[w],0===w%2?(y=g.o_("<html>"+p+"</html>"),y.getElementsByTagName("parsererror").length?
(F=y.createElement("span"),F.appendChild(y.createTextNode(p))):F=y.firstChild,rFa(this,r,n-(r-m),l,x,0<w,F,f,c)):r=u2(p)+h}G2.lastIndex=0}}return c};
var EFa=/^NOTE/,DFa=/(?:\r\n|\r|\n){2,}/,G2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),FFa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.u(v2,g.B);v2.prototype.clear=function(){this.u&&this.u.dispose();this.u=null};
v2.prototype.reset=function(){this.u&&this.u.reset()};
v2.prototype.ca=function(){g.B.prototype.ca.call(this);this.clear()};var F2={windowColor:"#080808",windowOpacity:0,textAlign:2,Uh:7,Vg:50,Gi:100,Hc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(y2,g.hO);g.k=y2.prototype;g.k.ca=function(){if(this.I||this.Z){var a=this.J.fd();a&&!a.ma()&&a.Bq()}else AFa(this,!1);g.hO.prototype.ca.call(this)};
g.k.Un=function(){return this.Ha?this.I||this.Z:wFa(this)||z2(this)?!0:vFa(this)};
g.k.load=function(){var a=this;g.hO.prototype.load.call(this);var b=!g.P(this.B.experiments,"web_player_captions_track_list_changed_killswitch");this.K=this.player.getAudioTrack();if(this.C)this.u&&(this.wa.clear(),this.I?xFa(this,!0):3!==this.player.getPresentingPlayerType()&&this.C.vu(this.u,"json3",function(d,e,f,h){if(d){a.C.CG()&&(a.W=[],a.J.Re("captions"),g.pn(a.X),a.wa.reset());var l=a.wa;f=f||0;h=h||0;if(l.B.Y("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.gv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),s2(d)||(d=g.Ze(new Uint8Array(d))))}}else"string"===typeof d||s2(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.gv(m,0,1835295092))&&m.size?g.Ze(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!s2(n))throw Error("Invalid binary caption track data");l.u||(l.u=new r2(r,e));var t=l.u.C(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.u||(l.u=new t2),p=l.u.C(e,r),.01>Math.random()&&g.Pr(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.u||(l.u=new a2(uFa(e)));n=l.u.C(p,f);break b}catch(G){g.ct(G);n=[];break b}r=g.o_(p);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=p;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.u||(l.u=new V1(uFa(e),l.B));n=l.u.C(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");y.params=p;throw y;}var F=Error("Invalid caption track data");F.params=p;throw F;}t=n}var D=t}catch(G){g.ct(G),l.clear(),D=[]}else D=[];a.player.Jd(D);!a.da||a.Z||C2(a)||g.HD(a.B)||g.ID(a.B)||(g.un(a.ea),D=VEa({Uh:0,Vg:5,Gi:5,Lk:2,textAlign:0,Ve:0,lang:"en-GB"}),a.ka=[D],l=["Click "," for settings"],a.Aa||(t=new g.PL(g.dM()),g.C(a,t),a.Aa=t.element),t=D.end-D.start,(e=g.UH(a.u))&&
a.ka.push(new R1(D.start,t,0,D.id,e)),a.ka.push(new R1(D.start,t,0,D.id,l[0]),new R1(D.start,t,0,D.id,a.Aa,!0),new R1(D.start,t,0,D.id,l[1],!0)),a.player.Jd(a.ka),g.sn(a.ea));!a.da||a.Z||C2(a)||(g.ZD(a.B)?(0,g.N_)(!0):D2(a,"module-enabled",!0),a.K&&(a.K.F=a.u),a.player.eo());a.da=!1}}),!b||this.I||this.Z||C2(this)||this.player.va("captionschanged",E1(this.u))),b||(this.u&&!C2(this)?this.player.va("captionschanged",E1(this.u)):this.player.va("onCaptionsTrackListChanged"));
else{var c;this.Ga?c=new M1(this.videoData.u,this.player):this.Ua?c=new J1(this.B,this.videoData,this.player.getAudioTrack()):c=new N1(this.videoData.ih,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.B.captionsLanguagePreference||g.YI(this.videoData,"yt:cc_default_lang")||this.B.We,this.videoData.Yo,this.B);this.C=c;g.C(this,this.C);c.wu(function(){var d;wFa(a)||a.da||vFa(a)?d=B2(a,a.da):z2(a)&&(d=A2(a));if(a.I||a.Z){for(var e=G1(a.C.B,!0),f=[],h=0;h<e.length;h++){var l=e[h],
m=g.Ge("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.UH(l));m.setAttribute("srclang",F1(l));m.setAttribute("id",l.toString());a.Z||m.setAttribute("src",a.C.Vo(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.J.fd();d.qq(f);f=d.Xd();a.Ia&&a.ga.P(f.textTracks,"change",a.aQ)}else!a.u&&d&&E2(a,d),a.player.va("onCaptionsTrackListChanged"),a.player.va("onApiChange")})}};
g.k.unload=function(){this.I&&this.u?xFa(this,!1):(this.ea&&g.un(this.ea),this.player.Re("captions"),this.W=[],this.C&&this.C.Tk(),this.wa.clear(),this.N&&this.player.Jd(this.N),this.UA());g.hO.prototype.unload.call(this);this.player.eo();this.player.va("captionschanged",{})};
g.k.create=function(){this.Un()&&this.load()};
g.k.aQ=function(){for(var a=this.J.fd().Xd().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=G1(this.C.B,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.u:null)!==b&&E2(this,b,!0)};
g.k.JR=function(){!this.u&&this.I||this.unload()};
g.k.yd=function(a){this.W.push(a);g.pn(this.X)};
g.k.qf=function(a){g.lb(this.W,a);this.C instanceof M1&&this.C.I&&this.player.kg([a]);g.pn(this.X)};
g.k.JQ=function(a){if(a instanceof S1){var b=this.U[a.id];b&&b.B!==a&&(b.dispose(),delete this.U[a.id],b=null);b||(b=yFa(this,a))&&(this.U[a.id]=b)}else b=a.windowId,this.la[b]||(this.la[b]=[]),this.la[b].push(a)};
g.k.RQ=function(){zFa(this,this.ka);this.ka=null};
g.k.KH=function(){var a=this;this.X.stop();g.Rb(this.la);this.W.sort(g.wG);var b=this.W;if(this.N){var c=g.Ne(b,function(d){return-1===this.N.indexOf(d)},this);
c.length&&(b=c)}g.Bb(b,this.JQ,this);g.Db(this.U,function(d,e){a.la[e]?(d.element.parentNode||(d instanceof Q1||d instanceof P1||g.Gb(a.U,function(f,h){h!==e&&f.B.params.Uh===d.B.params.Uh&&f.B.params.Vg===d.B.params.Vg&&f.B.params.Gi===d.B.params.Gi&&(f.dispose(),delete a.U[h]);return h===e},a),g.WN(a.player,d.element,4)),d.Wp(a.la[e])):(d.dispose(),delete a.U[e])},this)};
g.k.VQ=function(){w2(this,{},!0);g.P(this.B.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.va("captionssettingschanged")};
g.k.TJ=function(){var a=F2.Hc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.gi?3:a.bold?1:a.gi?2:0,textOpacity:a.textOpacity,windowColor:F2.windowColor,windowOpacity:F2.windowOpacity};var b=x2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.RH=function(a,b){var c={};g.Sa(c,x2(this,"display-settings"));g.Sa(c,a);w2(this,c,b);this.player.va("captionssettingschanged")};
g.k.UA=function(){!this.I&&this.loaded&&(g.Db(this.U,function(a,b){a.dispose();delete this.U[b]},this),this.KH())};
g.k.He=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ee(b,-2,4);this.RH({fontSizeIncrement:c});return c;case "reload":b&&!this.I&&E2(this,this.u,!0);break;case "stickyLoading":void 0!==b&&this.B.C&&(g.ZD(this.B)?(0,g.N_)(!!b):D2(this,"module-enabled",!!b));break;case "track":if(!this.C)return{};if(b){if(this.I)break;if(!g.Na(b))break;if(g.Qb(b)){E2(this,null,!0);break}for(var d=G1(this.C.B,!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==
b.languageName||(c=b.translationLanguage?EEa(f,b.translationLanguage):f)}!c||c===this.u&&this.loaded||E2(this,c,!0)}else return this.loaded&&this.u&&!C2(this)?E1(this.u):{};return"";case "tracklist":return this.C?g.Mc(G1(this.C.B,!(!b||!b.includeAsr)),function(h){return E1(h)}):[];
case "translationLanguages":return this.C?this.C.F.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.I||void 0===b||AFa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.B.C&&a.push("stickyLoading");return a};
g.k.ky=function(){var a=this.u;return a?{cc:a.vssId}:{}};
g.k.yR=function(){this.loaded&&this.u&&!C2(this)?(g.ZD(this.B)?(0,g.N_)(!1):D2(this,"module-enabled",!1),this.unload(),z2(this,!0)&&E2(this,A2(this),!1)):E2(this,C2(this)||!this.u?B2(this,!0):this.u,!0)};
g.k.FN=function(){var a=C2(this);z2(this,a)?E2(this,this.player.getAudioTrack().B,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Un()&&(a?E2(this,B2(this),!1):this.load()))};g.nO.captions=y2;})(_yt_player);
